// Generated by gencpp from file delta_arduino/cmdAngle.msg
// DO NOT EDIT!


#ifndef DELTA_ARDUINO_MESSAGE_CMDANGLE_H
#define DELTA_ARDUINO_MESSAGE_CMDANGLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace delta_arduino
{
template <class ContainerAllocator>
struct cmdAngle_
{
  typedef cmdAngle_<ContainerAllocator> Type;

  cmdAngle_()
    : theta1(0.0)
    , theta2(0.0)
    , theta3(0.0)  {
    }
  cmdAngle_(const ContainerAllocator& _alloc)
    : theta1(0.0)
    , theta2(0.0)
    , theta3(0.0)  {
  (void)_alloc;
    }



   typedef float _theta1_type;
  _theta1_type theta1;

   typedef float _theta2_type;
  _theta2_type theta2;

   typedef float _theta3_type;
  _theta3_type theta3;




  typedef boost::shared_ptr< ::delta_arduino::cmdAngle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::delta_arduino::cmdAngle_<ContainerAllocator> const> ConstPtr;

}; // struct cmdAngle_

typedef ::delta_arduino::cmdAngle_<std::allocator<void> > cmdAngle;

typedef boost::shared_ptr< ::delta_arduino::cmdAngle > cmdAnglePtr;
typedef boost::shared_ptr< ::delta_arduino::cmdAngle const> cmdAngleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::delta_arduino::cmdAngle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::delta_arduino::cmdAngle_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace delta_arduino

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'delta_arduino': ['/home/marvin/catkin_ws/src/delta/delta_arduino/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::delta_arduino::cmdAngle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::delta_arduino::cmdAngle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delta_arduino::cmdAngle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::delta_arduino::cmdAngle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delta_arduino::cmdAngle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::delta_arduino::cmdAngle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::delta_arduino::cmdAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6b72178218fbe6abc22ec5b1c7a40d8";
  }

  static const char* value(const ::delta_arduino::cmdAngle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6b72178218fbe6aULL;
  static const uint64_t static_value2 = 0xbc22ec5b1c7a40d8ULL;
};

template<class ContainerAllocator>
struct DataType< ::delta_arduino::cmdAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "delta_arduino/cmdAngle";
  }

  static const char* value(const ::delta_arduino::cmdAngle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::delta_arduino::cmdAngle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 theta1\n\
float32 theta2\n\
float32 theta3\n\
";
  }

  static const char* value(const ::delta_arduino::cmdAngle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::delta_arduino::cmdAngle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.theta1);
      stream.next(m.theta2);
      stream.next(m.theta3);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct cmdAngle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::delta_arduino::cmdAngle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::delta_arduino::cmdAngle_<ContainerAllocator>& v)
  {
    s << indent << "theta1: ";
    Printer<float>::stream(s, indent + "  ", v.theta1);
    s << indent << "theta2: ";
    Printer<float>::stream(s, indent + "  ", v.theta2);
    s << indent << "theta3: ";
    Printer<float>::stream(s, indent + "  ", v.theta3);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DELTA_ARDUINO_MESSAGE_CMDANGLE_H
